.TH diet 1 "April 2001"
.SH NAME
.PP
diet \- mangle gcc command line arguments
.SH SYNOPSIS
.PP
.B diet
[\fInormal gcc command line\fP]
.SH DESCRIPTION
.PP
Diet is a small wrapper around gcc.  It will try to look at the command
line you specify and try to mangle it so that gcc will compile against
the diet libc header files and link against the diet libc itself.

diet tries to be smart for cross compiling.  If the first argument is
not gcc but sparc-linux-gcc, diet will guess that you want to cross
compile for sparc and use bin-sparc/dietlibc.a instead of the dietlibc.a
for your default architecture.
.SH AUTHOR
Felix von Leitner <felix-dietlibc@fefe.de>
